module.exports = {
  HIDE_SELECTION_GRID: 'HIDE_SELECTION_GRID',
  SHOW_SELECTION_GRID: 'SHOW_SELECTION_GRID',
  DRAW_SELECTION_GRID: 'DRAW_SELECTION_GRID',
  
  HIDE_CONTROL_PANEL: 'HIDE_CONTROL_PANEL',
  SHOW_CONTROL_PANEL: 'SHOW_CONTROL_PANEL',
  DRAW_CONTROL_PANEL: 'DRAW_CONTROL_PANEL',

  DRAW_BAR_CHART: 'DRAW_BAR_CHART',
  DRAW_BAR_SWAP: 'DRAW_BAR_SWAP',
  DRAW_BAR_HEIGHT: 'DRAW_BAR_HEIGHT',
  DRAW_BAR_SECTION: 'DRAW_BAR_SECTION',
  DRAW_COMPARE: 'DRAW_COMPARE',

  UPDATE_BAR_HEIGHT: 'UPDATE_BAR_HEIGHT',
  UPDATE_SORT_METHOD: 'UPDATE_SORT_METHOD',

  SORT_ARRAY: 'SORT_ARRAY',
  SHUFFLE_ARRAY: 'SHUFFLE_ARRAY',
  REVERSE_ARRAY: 'REVERSE_ARRAY',

  INCREMENT_BARS: 'INCREMENT_BARS',
  DECREMENT_BARS: 'DECREMENT_BARS',
  INCREMENT_MAX_VALUE: 'INCREMENT_MAX_VALUE',
  DECREMENT_MAX_VALUE: 'DECREMENT_MAX_VALUE',
  INCREMENT_DELAY: 'INCREMENT_DELAY',
  DECREMENT_DELAY: 'DECREMENT_DELAY',
}